### ISSUE TITLE
[FEATURE REQUEST] Contribution Guidelines

### ISSUE THREAD

**Issue by darigovresearch** [Robbbb/VectorRuler#10]
First of all this is a great project and is really useful thanks for taking the time to make it!

We see that this project was built a long time ago, are you still interested in accepting pull requests for feature improvements and bug fixes from the community?

If so we may have some pull requests or are happy to help build out features/make corrections as they come along.

Happy to make a pull requests with things like the following to make it easier for people to get started
- [x] Contribution guidelines
- [x] Issue templates
- [x] Pull request templates

**Comment by PeterHindes** [comment]
I am not the maintainer. But I have the big feature request issue open right now. I would love it if you could come on board, I think the maintainer would be interested in your help, as in issue #8 he mentioned that he does not have the coder for the project that originally helped with the project.

**Comment by darigovresearch** [comment]
Yeah would be happy to become a maintainer to help field more technical feature requests and fielding pull requests and the like if added as a collaborator to the repository (meaning less work for @Robbbb to do and we're used to doing it, see our other open source projects).

@PeterHindes issue #8 is probably a project in an of itself (as it may not strictly be a ruler) but investigating into the code base of this repository and the open source license would probably mean that we would be able to make that given the time.

For example we also wanted to make a vector protractor generator in a similar format but because it is not a ruler we would do it in a different project than merging it into this project.

**Comment by Robbbb** [comment]
Sorry for the delay.
I agree that a radius gauge is not a ruler as much as a separate tool.
I am happy to add collaborators or merge pull requests as they come, I do not know JavaScript really, I did this with significant help from a friend. 
if you want to write guideline, I will happily merge them! I am forever thrilled that folks find this tool useful!

**Comment by Robbbb** [comment]
@darigovresearch Do you still want to be a contributor? I'd love the help, I am pretty confused by some of the issues 
let me know!

**Comment by darigovresearch** [comment]
@Robbbb yeah would be happy to help where we can if you add us as a maintainer

**Comment by Robbbb** [comment]
Rad! I have added you.
Here is my dream list, and I'd love to help where I can! maybe we can have a zoom sometime?

- A way to set the base to decimal, not fractional, as soon as someone selects the metric radio button [see here](https://github.com/Robbbb/VectorRuler/issues/5) (currently people are given a ruler with 1/8cm which is pretty obscure)
- Adding a checkbox that makes the 5mm mark a different height than the other mm marks, as common on metric rulers
- A mirror vertical button to help people who are making dual-unit rulers [see here](https://github.com/Robbbb/VectorRuler/issues/5)
- A dropdown 'advanced tab' to hide the 'draw redundant lines' feature and as a place to keep the DPI setting currently waiting merger in the [pull request world ](https://github.com/Robbbb/VectorRuler/pull/13)(I fear it will confuse most users and only be needed for very few)
- A privacy-respecting hit counter for how many people have ever used this thing to keep us motivated in terms of maintaining it
- Zooming support in the preview, so large rulers are visible
- PNG and DXF(Standard 2D CAD format) support would be amazing, but may not be very easy.

**Comment by darigovresearch** [comment]
@Robbbb thanks for the add. All good feature requests, would suggest opening individual issues for each of your requests as it makes it easier for people to see where they can contribute than having them all in one issue here.

That in conjunction with the items mentioned here https://github.com/Robbbb/VectorRuler/issues/10#issue-675490841 may bring you solutions faster than you think

**Comment by darigovresearch** [comment]
Pull requests #22 #23 & #25 resolve all items in this issue
