### ISSUE TITLE
[BUG] Preview Stretched Out and weird looking

### ISSUE THREAD

**Issue by Robbbb** [Robbbb/VectorRuler#12]
![image](https://user-images.githubusercontent.com/2336553/121132297-d0d52580-c7e5-11eb-80b1-db8f243b95ec.png)
I have no idea what caused this or how to address it, I do not really know what I am doing, but this issue seems new.
I am using Brave, but it also looks fuzzy and wrong on Safari. 
Any ideas?

**Comment by darigovresearch** [comment]
Tried to replicate this issue on brave but couldn't, is anyone else having this issue?

**Comment by Robbbb** [comment]
On recent attempts, I can no longer replicate it. I think we can close it out!
Thanks for all the energy you are bringing to this project!
