### ISSUE TITLE
[BUG/TYPO] Non consistent spacing features in readme

### ISSUE THREAD

**Issue by darigovresearch** [Robbbb/VectorRuler#27]
**Describe the bug**
Spacing between bullet points in the readme is not consistent

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the readme to preview

**Expected behaviour**
Bullet points pacing should be equal

**Screenshots**
![image](https://user-images.githubusercontent.com/30328618/134799563-f38b1eb0-d37f-4c16-8fc6-9533ba7e29ab.png)

**Additional context**
This is a good first issue for someone looking to contribute to an open source project and pull requests to fix this is highly encouraged

**Comment by priyanka010392** [comment]
@darigovresearch, I would like to take this up. Could you please assign it to me?
