### ISSUE TITLE
[FEATURE REQUEST] Left Hand Ruler

### ISSUE THREAD

**Issue by geoffsim** [Robbbb/VectorRuler#37]
Being able to create a left hand ruler would be useful

**Comment by darigovresearch** [comment]
Hey @geoffsim, thanks for reaching out & raising this. Could you advise further on what a left hand ruler requires?

Is it that the numbers count up from right to left or additional features to make it more accessible?

**Comment by geoffsim** [comment]
Yes, count from right to left for a left handed ruler.

**Comment by darigovresearch** [comment]
Thanks for the confirmation! Would you be interested in making a pull request?
