### ISSUE TITLE
Fractions in metric?

### ISSUE THREAD

**Issue by myk3y** [Robbbb/VectorRuler#5]
Rather than 1/8 of a cm, wouldn’t mm scale be more appropriate?

**Comment by myk3y** [comment]
Doh! My mistake.

**Comment by Robbbb** [comment]
You make a good point, that metric mode should default to decimal, as I would guess there are only a handful of misguided souls in the world who crave a fractional metric ruler. I don’t actually know JavaScript, this is my first and only project with it. It would also be cool to have a taller tick at 5mm option, as is common on metric rules. It is cool to use folks using this generator! I’d love to see photos of some ways people are using it!

**Comment by myk3y** [comment]
The other thing I had a problem with is creating a doubled-sided ruler with cm on one side and inches on the other.

A way to decide which side to orient it, would be nice.

It wasn't too hard in AI to move it all around and would have been easier if I was more adept, but it still added ten minutes of mucking about.

This is what I was making - a laser calibration test ruler for Shenhui laser.

![screen shot 2019-03-02 at 6 51 24 am](https://user-images.githubusercontent.com/9743808/53670998-a10a4f80-3cb7-11e9-8cac-86011783248b.png)

**Comment by Robbbb** [comment]
That looks great!
I will implement a mirror feature if I ever revisit this project and
relearn JS.

Thanks for the photo!

**Comment by myk3y** [comment]
No worries. Thank you for taking the time to make the tool.
