### ISSUE TITLE
Generate Radious ruler

### ISSUE THREAD

**Issue by PeterHindes** [Robbbb/VectorRuler#8]
generate rulers for measuring curves and circles.

**Comment by PeterHindes** [comment]
Why was this closed?

**Comment by Robbbb** [comment]
Sorry, I didn't know what you meant. 
Care to clarify? Examples of such rulers? Do you mean circumferential tapes which indicate diameter? 

Also, I would have no idea how to implement it. I built this tool with help I no longer have and do not know Javascript.

**Comment by PeterHindes** [comment]
I see that you no longer have help with coding this and your situation makes it so that you cannot address this issue, however I think the issue should stay open so if someone else wants to solve it they can.
As for what I meant I would think something like [this](https://www.amazon.com/Template-Plastic-Drawing-Templates-Supplies/dp/B07F5P591D) would do the trick. I want to be able to use a symetric curve to calculate the resulting circles radius.

**Comment by Robbbb** [comment]
I am closing this as I consider it out of scope and highly specialized. 
Thanks for the suggestion!
